---
title: "Exploratory plots"
author: "Leon Di Stefano"
date: "11/08/2017"
output: html_document
---

## Load data

Works as-is when pasted into the terminal with 
```
setwd("~/Projects/sv_benchmark")
```

Also knits OK.

```{r}
source("global.R")
source("shinyCache2.R")
source("libplot.R")

require("tidyverse")
require("cowplot")

caller_ids <- c(
	"00000000000000000000000000000001",
	"16c58fbcc5633564b10ebe8f78d87883",
	"40c68f29b6d7cb2358f31a7073250406",
	"43a13d07730deb934e9fc01e3b3cd26f",
	"8dcad8fe04f4ebc0ad3254ab4420cdc8",
	"9d134f160ac68c0445002fbb78db4a5e",
	"acd889cc16741fb0fba62faa4f7005f3",
	"b1112f1c3cbd28c464f58fc5c5c02f9b")

data_dir <- "../data.chm"
    
    
callmat <- .LoadCallMatrixForIds(
	datadir = data_dir,
	metadata = LoadCachedMetadata(data_dir),
	ids = caller_ids,
	ignore.interchromosomal = TRUE, 
	mineventsize = 51, 
	maxeventsize = NULL,
	maxgap = 200,
	sizemargin = 0.25,
	ignore.strand = TRUE,
	grtransform = .primaryHumanOnly,
	grtransformName = "test")
```

```{r}
getCacheRootPath()
```

### As data frame

```{r}
callmat_df <-
    callmat %>%
    as.data.frame() %>%
    as.tbl()

callmat_df
```

### Some exploration

```{r}
sum(callmat_df$QUAL == -1)
```

Showing the different scales of the (query) QUAL scores, and the different
counts of variants called by caller:

```{r}
qplot(log10(QUAL), data = callmat_df) + 
    facet_wrap(
        ~Id,
        scales = "free_y")
```


## As long data frame

```{r}
callmat_df_long <-
    callmat_df %>% 
    gather(
        17:(17 + length(caller_ids) - 1), 
        key = subject_vcf_id, 
        value = subject_vcf_qual) %>%
    filter(
        subject_vcf_qual != -1) %>%
    rename(
        query_vcf_qual = QUAL,
        query_vcf_id = Id)

callmat_df_long
```

#### Truth-as-query df

```{r}
truth_query_df <-
    callmat_df_long %>%
    filter(
        query_vcf_id == "00000000000000000000000000000001")
```

### Truth stacked barplot

```{r}
## What does VcfId represent?
truth_query_df %>% group_by(vcfId) %>% summarise(count = n())
## Most of these are 2.
```
```{r}
(truth_query_df %>% group_by(vcfId) %>% summarise(count = n()))$count %>% table
```

### Matrix of rank correlations

This is not doing what I want/hoped:

```{r}
corr_df <- 
    callmat_df_long %>% 
    group_by(query_vcf_id, subject_vcf_id) %>% 
    summarise(
        spearman_corr = cor(
            query_vcf_qual, 
            subject_vcf_qual,
            method = "spearman"))

corr_df
```










